name: CDK

on:
  push:
    branches: [stable]
    paths: 
        - 'cdk-*/**'
  pull_request:
    branches: [stable] 
    paths: 
        - 'cdk-*/**'

env:
  AWS_REGION: af-south-1
  AWS_DEFAULT_REGION: af-south-1

permissions:
  id-token: write
  contents: read

jobs:
  CDK:
    runs-on: [ubuntu-latest]
    steps:
      - name: AWS SETUP
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::978251882572:role/GitHubActionsDeploymentRole #NEVER CHANGE THIS
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{env.AWS_REGION}}

      - name: CHECKOUT
        uses: actions/checkout@v4

      - name: SETUP NODE
        uses: actions/setup-node@v4
        with: 
          node-version: 24
          cache: 'npm'
          cache-dependency-path: cdk-*/package-lock.json
        
      - name: DEPLOY CDK
        run: |
          cd cdk-*
          npm i
          npx cdk deploy --require-approval never || (npx cdk bootstrap && npx cdk deploy --require-approval never)