name: CICD

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable] 

env:
  AWS_REGION: af-south-1
  AWS_DEFAULT_REGION: af-south-1
  EC2_USER_Y_HOST: ec2-user@susnet.co.za

permissions:
  id-token: write
  contents: read

jobs:
  CICD:
    runs-on: [ubuntu-latest]
    steps:
      - name: AWS SETUP
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::978251882572:role/GitHubActionsDeploymentRole #NEVER CHANGE THIS
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{env.AWS_REGION}}
      
      - name: GETTING THE KEY
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            THE_KEY, the-key
          parse-json-secrets: false
          
      - name: SETTING UP THE KEY
        run: |
          mkdir -p ~/.ssh
          echo "${{env.THE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: RUN PRE.SH SCRIPT ON EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.EC2_USER_Y_HOST }} "curl -o- https://raw.githubusercontent.com/miniconomy2025/susnet/refs/heads/stable/pre.sh | sudo bash"
